CREATE TABLE JDBC_TBL(ID NUMBER, NAME VARCHAR, PERCENTAGE DECIMAL);
INSERT INTO JDBC_TBL VALUES(1001, 'Sachin', 90.18); 
INSERT INTO JDBC_TBL VALUES(1002, 'Sehbag', 80.18);
SELECT * FROM JDBC_TBL;
CREATE TABLE JDBC_PROFILE_TBL(NAME VARCHAR, IMAGE BLOB);